name: zadam_delivery
description: ZadGo - نظام إدارة توصيل طلبات
publish_to: 'none'
version: 4.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 3.8.0
  firebase_auth: 5.3.3
  cloud_firestore: 5.5.0
  firebase_messaging: 15.1.5

  provider: ^6.1.2

  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  fl_chart: ^0.69.0

  uuid: ^4.5.1
  intl: ^0.19.0

  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_square.png