org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=384m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
kotlin.incremental=false
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
org.gradle.vfs.watch=false